/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimularRouteImport } from './routes/simular'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const SimularRoute = SimularRouteImport.update({
  id: '/simular',
  path: '/simular',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar': typeof ConfirmarRoute
  '/simular': typeof SimularRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar': typeof ConfirmarRoute
  '/simular': typeof SimularRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar': typeof ConfirmarRoute
  '/simular': typeof SimularRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/confirmar' | '/simular'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/confirmar' | '/simular'
  id: '__root__' | '/' | '/cadastro' | '/confirmar' | '/simular'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ConfirmarRoute: typeof ConfirmarRoute
  SimularRoute: typeof SimularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simular': {
      id: '/simular'
      path: '/simular'
      fullPath: '/simular'
      preLoaderRoute: typeof SimularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ConfirmarRoute: ConfirmarRoute,
  SimularRoute: SimularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
